name: cfn-plan-apply

on:
  pull_request:
    paths:
      - "cloudformation/**"
      - ".github/workflows/cfn-plan-apply.yml"
  push:
    branches: ["main"]
    paths:
      - "cloudformation/**"
      - ".github/workflows/cfn-plan-apply.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: ap-southeast-2
  ENV: dev
  PREFIX: demo-eks
  VPC_STACK: demo-eks-vpc-dev
  EKS_STACK: demo-eks-eks-dev
  NG_STACK: demo-eks-nodegroup-dev
  ARGO_STACK: demo-eks-argocd-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::685801731369:role/github-oidc-deployer
          aws-region: ${{ env.AWS_REGION }}

      - name: Set AWS CLI behavior
        run: |
          echo "AWS_PAGER=" >> $GITHUB_ENV
          echo "AWS_RETRY_MODE=standard" >> $GITHUB_ENV
          echo "AWS_MAX_ATTEMPTS=2" >> $GITHUB_ENV

      - name: Validate CFN templates
        run: |
          aws cloudformation validate-template --template-body file://cloudformation/vpc.yaml
          aws cloudformation validate-template --template-body file://cloudformation/eks-cluster.yaml
          aws cloudformation validate-template --template-body file://cloudformation/nodegroup.yaml
          aws cloudformation validate-template --template-body file://cloudformation/argocd-bootstrap.yaml

      # ---------- VPC ----------
      - name: Preflight - wait if VPC stack is IN_PROGRESS
        run: |
          set -e
          STATUS=$(aws cloudformation describe-stacks --stack-name "${VPC_STACK}" \
            --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NONE")
          echo "VPC stack status: $STATUS"
          case "$STATUS" in
            CREATE_IN_PROGRESS) aws cloudformation wait stack-create-complete --stack-name "${VPC_STACK}" ;;
            UPDATE_IN_PROGRESS|UPDATE_COMPLETE_CLEANUP_IN_PROGRESS) aws cloudformation wait stack-update-complete --stack-name "${VPC_STACK}" ;;
            DELETE_IN_PROGRESS) aws cloudformation wait stack-delete-complete --stack-name "${VPC_STACK}" ;;
            *) echo "No wait needed." ;;
          esac

      - name: Create/Update VPC stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/vpc.yaml \
            --stack-name "${VPC_STACK}" \
            --parameter-overrides file://cloudformation/parameters/${ENV}/vpc.json \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Get VPC outputs
        id: vpc
        run: |
          set -euo pipefail
          VAL=$(aws cloudformation describe-stacks --stack-name "${VPC_STACK}" \
            --query "Stacks[0].Outputs[?OutputKey=='PublicSubnetIds'].OutputValue | [0]" \
            --output text)
          VAL_CLEAN=$(echo "$VAL" | tr -d '[:space:]')
          if [ -z "$VAL_CLEAN" ] || [ "$VAL_CLEAN" = "None" ]; then
            echo "ERROR: Output 'PublicSubnetIds' is missing/empty on stack ${VPC_STACK}" >&2
            aws cloudformation describe-stacks --stack-name "${VPC_STACK}" \
              --query "Stacks[0].Outputs" --output table || true
            exit 1
          fi
          echo "public_subnets=$VAL_CLEAN" >> "$GITHUB_OUTPUT"

      # ---------- EKS CONTROL PLANE ----------
      - name: Preflight - heal/delete stuck EKS stack
        run: |
          set -euo pipefail
          STACK="${EKS_STACK}"
          STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK" \
            --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NONE")
          echo "EKS stack status: $STATUS"
          if [[ "$STATUS" == "ROLLBACK_FAILED" || "$STATUS" == "ROLLBACK_COMPLETE" || "$STATUS" == "DELETE_FAILED" ]]; then
            aws cloudformation delete-stack --stack-name "$STACK" || true
            if ! aws cloudformation wait stack-delete-complete --stack-name "$STACK"; then
              mapfile -t FAILS < <(
                aws cloudformation describe-stack-events --stack-name "$STACK" --max-items 200 \
                  --query "reverse(StackEvents)[?contains(ResourceStatus,'DELETE_FAILED')].[LogicalResourceId]" \
                  --output text | awk '!seen[$0]++'
              )
              [[ ${#FAILS[@]} -gt 0 ]] && aws cloudformation delete-stack --stack-name "$STACK" --retain-resources ${FAILS[*]} || true
              aws cloudformation wait stack-delete-complete --stack-name "$STACK" || true
            fi
          fi

      - name: Create/Update EKS cluster
        run: |
          PARAMS=$(jq -r '.Parameters | to_entries[] | "\(.key)=\(.value)"' cloudformation/parameters/${ENV}/eks.json)
          aws cloudformation deploy \
            --template-file cloudformation/eks-cluster.yaml \
            --stack-name "${EKS_STACK}" \
            --parameter-overrides $PARAMS PublicSubnetIds="${{ steps.vpc.outputs.public_subnets }}" \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Wait for EKS to be ACTIVE
        run: |
          CLUSTER=$(aws cloudformation describe-stacks --stack-name "${EKS_STACK}" \
            --query "Stacks[0].Outputs[?OutputKey=='ClusterName'].OutputValue" --output text)
          aws eks wait cluster-active --name "$CLUSTER"

      - name: Ensure EKS access API is enabled (required for AccessEntry)
        run: |
          set -euo pipefail
          CLUSTER=$(aws cloudformation describe-stacks --stack-name "${EKS_STACK}" \
            --query "Stacks[0].Outputs[?OutputKey=='ClusterName'].OutputValue" --output text)
          MODE=$(aws eks describe-cluster --name "$CLUSTER" \
            --query 'cluster.accessConfig.authenticationMode' --output text 2>/dev/null || echo "UNKNOWN")
          echo "Current auth mode: $MODE"
          if [ "$MODE" != "API" ] && [ "$MODE" != "API_AND_CONFIG_MAP" ]; then
            aws eks update-cluster-config --name "$CLUSTER" \
              --access-config authenticationMode=API_AND_CONFIG_MAP
            aws eks wait cluster-active --name "$CLUSTER"
          fi

      # ---------- NODEGROUP (BEFORE Argo) ----------
      - name: Preflight - heal/delete stuck Nodegroup stack
        run: |
          set -euo pipefail
          STACK="${NG_STACK}"
          STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK" \
            --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NONE")
          echo "Nodegroup stack status: $STATUS"
          if [[ "$STATUS" == "ROLLBACK_FAILED" || "$STATUS" == "ROLLBACK_COMPLETE" || "$STATUS" == "DELETE_FAILED" ]]; then
            aws cloudformation delete-stack --stack-name "$STACK" || true
            if ! aws cloudformation wait stack-delete-complete --stack-name "$STACK"; then
              mapfile -t FAILS < <(
                aws cloudformation describe-stack-events --stack-name "$STACK" --max-items 200 \
                  --query "reverse(StackEvents)[?contains(ResourceStatus,'DELETE_FAILED')].[LogicalResourceId]" \
                  --output text | awk '!seen[$0]++'
              )
              [[ ${#FAILS[@]} -gt 0 ]] && aws cloudformation delete-stack --stack-name "$STACK" --retain-resources ${FAILS[*]} || true
              aws cloudformation wait stack-delete-complete --stack-name "$STACK" || true
            fi
          fi

      - name: Create/Update node group
        run: |
          PARAMS=$(jq -r '.Parameters | to_entries[] | "\(.key)=\(.value)"' cloudformation/parameters/${ENV}/nodegroup.json)
          aws cloudformation deploy \
            --template-file cloudformation/nodegroup.yaml \
            --stack-name "${NG_STACK}" \
            --parameter-overrides $PARAMS PublicSubnetIds="${{ steps.vpc.outputs.public_subnets }}" \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Wait for at least one Ready node
        run: |
          set -euo pipefail
          CLUSTER=$(aws cloudformation describe-stacks --stack-name "${EKS_STACK}" \
            --query "Stacks[0].Outputs[?OutputKey=='ClusterName'].OutputValue" --output text)

          echo "Ensuring kubeconfig for $CLUSTER..."
          aws eks update-kubeconfig --name "$CLUSTER" --region "${AWS_REGION}"

          echo "Waiting for cluster API..."
          for i in {1..30}; do
            if kubectl version --request-timeout=10s >/dev/null 2>&1; then
              echo "API OK"; break
            fi
            echo "API not ready yet... ($i/30)"; sleep 5
          done

          echo "Waiting for at least 1 Ready node..."
          for i in {1..40}; do
            READY=$(kubectl get nodes --no-headers 2>/dev/null | awk '$2=="Ready"{c++} END{print c+0}')
            if [ "${READY:-0}" -ge 1 ]; then
              kubectl get nodes -o wide
              exit 0
            fi
            echo "No Ready nodes yet... ($i/40)"; sleep 15
          done
          echo "No Ready nodes after waiting."; exit 1

      # ---------- ARGO CD (after nodes exist) ----------
      - name: Preflight - heal/delete stuck ArgoCD stack
        run: |
          set -euo pipefail
          STACK="${ARGO_STACK}"
          STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK" \
            --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NONE")
          echo "ArgoCD stack status: $STATUS"
          if [[ "$STATUS" == "ROLLBACK_FAILED" || "$STATUS" == "ROLLBACK_COMPLETE" || "$STATUS" == "DELETE_FAILED" ]]; then
            aws cloudformation delete-stack --stack-name "$STACK" || true
            aws cloudformation wait stack-delete-complete --stack-name "$STACK" || true
          fi

      - name: Bootstrap Argo CD (CFN -> CodeBuild -> Argo install)
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/argocd-bootstrap.yaml \
            --stack-name "${ARGO_STACK}" \
            --parameter-overrides \
              ClusterName=demo-eks-dev \
              Region=${{ env.AWS_REGION }} \
              KubernetesNamespace=argocd \
              ExposeServerAsLB=true \
              SSMParamPrefix=/eks/${{ env.ENV }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Show ArgoCD stack failure events (if any)
        if: failure()
        run: |
          aws cloudformation describe-stack-events --stack-name "${ARGO_STACK}" \
            --max-items 60 \
            --query "StackEvents[?ends_with(ResourceStatus,'FAILED')].[Timestamp,LogicalResourceId,ResourceStatus,ResourceStatusReason]" \
            --output table || true

      - name: Show Lambda logs for Argo custom resource (auto-discover)
        if: failure()
        run: |
          set -euo pipefail
          REG="${AWS_REGION}"
          FN=$(aws cloudformation list-stack-resources \
            --region "$REG" \
            --stack-name "${ARGO_STACK}" \
            --query "StackResourceSummaries[?LogicalResourceId=='TriggerFn'].PhysicalResourceId | [0]" \
            --output text 2>/dev/null || echo "None")
          if [ -z "$FN" ] || [ "$FN" = "None" ]; then exit 0; fi
          echo "Trigger function: $FN"
          LG="/aws/lambda/${FN}"
          LS=$(aws logs describe-log-streams --region "$REG" --log-group-name "$LG" \
            --order-by LastEventTime --descending --max-items 1 \
            --query 'logStreams[0].logStreamName' --output text 2>/dev/null || echo "None")
          if [ -z "$LS" ] || [ "$LS" = "None" ]; then exit 0; fi
          echo "Log stream: $LS"
          aws logs get-log-events --region "$REG" --log-group-name "$LG" --log-stream-name "$LS" \
            --limit 10000 --output text | sed -E 's/^.*\t//' | tail -n 200

      - name: Show CodeBuild logs for Argo bootstrap (auto-discover)
        if: failure()
        run: |
          set -euo pipefail
          REG="${AWS_REGION}"
          PROJ=$(aws cloudformation list-stack-resources \
            --region "$REG" \
            --stack-name "${ARGO_STACK}" \
            --query "StackResourceSummaries[?ResourceType=='AWS::CodeBuild::Project'].PhysicalResourceId | [0]" \
            --output text 2>/dev/null || echo "None")
          if [ -z "$PROJ" ] || [ "$PROJ" = "None" ]; then exit 0; fi
          echo "Project: $PROJ"
          aws codebuild batch-get-projects --region "$REG" --names "$PROJ" \
            --query 'projects[0].{ServiceRole:serviceRole,Env:environment.environmentVariables}' --output table || true
          BID=$(aws codebuild list-builds-for-project --region "$REG" --project-name "$PROJ" \
            --sort-order DESCENDING --max-results 5 --query 'ids[0]' --output text 2>/dev/null || echo "None")
          if [ -z "$BID" ] || [ "$BID" = "None" ]; then exit 0; fi
          echo "Latest build: $BID"
          LG=$(aws codebuild batch-get-builds --region "$REG" --ids "$BID" --query 'builds[0].logs.groupName' --output text)
          LS=$(aws codebuild batch-get-builds --region "$REG" --ids "$BID" --query 'builds[0].logs.streamName' --output text)
          if [ -z "$LG" ] || [ "$LG" = "None" ] || [ -z "$LS" ] || [ "$LS" = "None" ]; then exit 0; fi
          echo "--- LOG TAIL (100) ---"
          aws logs get-log-events --region "$REG" --log-group-name "$LG" --log-stream-name "$LS" \
            --limit 10000 --output text | sed -E 's/^.*\t//' | tail -n 100