name: cfn-plan-apply

on:
  pull_request:
    paths:
      - "cloudformation/**"
      - ".github/workflows/cfn-plan-apply.yml"
  push:
    branches: ["main"]
    paths:
      - "cloudformation/**"
      - ".github/workflows/cfn-plan-apply.yml"

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: ap-southeast-2
  ENV: dev
  PREFIX: demo-eks
  VPC_STACK: demo-eks-vpc-dev
  EKS_STACK: demo-eks-eks-dev
  NG_STACK:  demo-eks-nodegroup-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::685801731369:role/github-oidc-deployer
          aws-region: ${{ env.AWS_REGION }}

      # ----- VPC (already exists, stays idempotent) -----
      - name: Create/Update VPC stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/vpc.yaml \
            --stack-name $STACK_NAME \
            --parameter-overrides file://cloudformation/parameters/${ENV}/vpc.json \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Get VPC outputs
        id: vpc
        run: |
          OUT=$(aws cloudformation describe-stacks --stack-name "${VPC_STACK}" --query "Stacks[0].Outputs")
          echo "public_subnets=$(echo $OUT | jq -r '.[] | select(.OutputKey==\"PublicSubnetIds\").OutputValue')" >> $GITHUB_OUTPUT

      # ----- EKS control plane -----
      - name: Create/Update EKS cluster
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/eks-cluster.yaml \
            --stack-name "${EKS_STACK}" \
            --parameter-overrides \
              file://cloudformation/parameters/${ENV}/eks.json \
              PublicSubnetIds=${{ steps.vpc.outputs.public_subnets }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Wait for EKS to be ACTIVE
        run: |
          CLUSTER=$(aws cloudformation describe-stacks --stack-name "${EKS_STACK}" \
            --query "Stacks[0].Outputs[?OutputKey=='ClusterName'].OutputValue" --output text)
          aws eks wait cluster-active --name "$CLUSTER"

      # ----- Node group -----
      - name: Create/Update node group
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/nodegroup.yaml \
            --stack-name "${NG_STACK}" \
            --parameter-overrides \
              file://cloudformation/parameters/${ENV}/nodegroup.json \
              PublicSubnetIds=${{ steps.vpc.outputs.public_subnets }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset