name: cfn-plan-apply

on:
  pull_request:
    paths:
      - "cloudformation/**"
      - ".github/workflows/cfn-plan-apply.yml"
  push:
    branches: ["main"]
    paths:
      - "cloudformation/**"
      - ".github/workflows/cfn-plan-apply.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  AWS_REGION: ap-southeast-2
  ENV: dev
  PREFIX: demo-eks
  VPC_STACK: demo-eks-vpc-dev
  EKS_STACK: demo-eks-eks-dev
  NG_STACK: demo-eks-nodegroup-dev
  ARGO_STACK: demo-eks-argocd-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::685801731369:role/github-oidc-deployer
          aws-region: ${{ env.AWS_REGION }}

      - name: Set AWS CLI behavior
        run: |
          echo "AWS_PAGER=" >> $GITHUB_ENV
          echo "AWS_RETRY_MODE=standard" >> $GITHUB_ENV
          echo "AWS_MAX_ATTEMPTS=2" >> $GITHUB_ENV

      - name: Validate CFN templates
        run: |
          aws cloudformation validate-template --template-body file://cloudformation/vpc.yaml
          aws cloudformation validate-template --template-body file://cloudformation/eks-cluster.yaml
          aws cloudformation validate-template --template-body file://cloudformation/nodegroup.yaml
          aws cloudformation validate-template --template-body file://cloudformation/argocd-bootstrap.yaml

      # ---------- PREFLIGHT: VPC ----------
      - name: Preflight - wait if VPC stack is IN_PROGRESS
        run: |
          set -e
          STATUS=$(aws cloudformation describe-stacks --stack-name "${VPC_STACK}" \
            --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NONE")
          echo "VPC stack status: $STATUS"
          case "$STATUS" in
            CREATE_IN_PROGRESS) aws cloudformation wait stack-create-complete --stack-name "${VPC_STACK}" ;;
            UPDATE_IN_PROGRESS|UPDATE_COMPLETE_CLEANUP_IN_PROGRESS) aws cloudformation wait stack-update-complete --stack-name "${VPC_STACK}" ;;
            DELETE_IN_PROGRESS) aws cloudformation wait stack-delete-complete --stack-name "${VPC_STACK}" ;;
            *) echo "No wait needed." ;;
          esac

      # ---------- VPC ----------
      - name: Create/Update VPC stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/vpc.yaml \
            --stack-name "${VPC_STACK}" \
            --parameter-overrides file://cloudformation/parameters/${ENV}/vpc.json \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Get VPC outputs
        id: vpc
        run: |
          set -euo pipefail
          VAL=$(aws cloudformation describe-stacks --stack-name "${VPC_STACK}" \
            --query "Stacks[0].Outputs[?OutputKey=='PublicSubnetIds'].OutputValue | [0]" \
            --output text)

          echo "Resolved PublicSubnetIds from ${VPC_STACK}: $VAL"

          # normalize & validate
          VAL_CLEAN=$(echo "$VAL" | tr -d '[:space:]')
          if [ -z "$VAL_CLEAN" ] || [ "$VAL_CLEAN" = "None" ]; then
            echo "ERROR: Output 'PublicSubnetIds' is missing/empty on stack ${VPC_STACK}" >&2
            echo "All outputs for debugging:" >&2
            aws cloudformation describe-stacks --stack-name "${VPC_STACK}" \
              --query "Stacks[0].Outputs" --output table || true
            exit 1
          fi

          echo "public_subnets=$VAL_CLEAN" >> "$GITHUB_OUTPUT"

      # ---------- PREFLIGHT: EKS ----------
      - name: Preflight - heal/delete stuck EKS stack
        run: |
          set -euo pipefail
          STACK="${EKS_STACK}"
          STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK" \
            --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NONE")
          echo "EKS stack status: $STATUS"
          if [[ "$STATUS" == "ROLLBACK_FAILED" || "$STATUS" == "ROLLBACK_COMPLETE" || "$STATUS" == "DELETE_FAILED" ]]; then
            aws cloudformation delete-stack --stack-name "$STACK" || true
            if ! aws cloudformation wait stack-delete-complete --stack-name "$STACK"; then
              mapfile -t FAILS < <(
                aws cloudformation describe-stack-events --stack-name "$STACK" --max-items 200 \
                  --query "reverse(StackEvents)[?contains(ResourceStatus,'DELETE_FAILED')].[LogicalResourceId]" \
                  --output text | awk '!seen[$0]++'
              )
              [[ ${#FAILS[@]} -gt 0 ]] && aws cloudformation delete-stack --stack-name "$STACK" --retain-resources ${FAILS[*]} || true
              aws cloudformation wait stack-delete-complete --stack-name "$STACK" || true
            fi
          fi

      - name: Create/Update EKS cluster
        run: |
          PARAMS=$(jq -r '.Parameters | to_entries[] | "\(.key)=\(.value)"' cloudformation/parameters/${ENV}/eks.json)
          aws cloudformation deploy \
            --template-file cloudformation/eks-cluster.yaml \
            --stack-name "${EKS_STACK}" \
            --parameter-overrides $PARAMS PublicSubnetIds="${{ steps.vpc.outputs.public_subnets }}" \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Wait for EKS to be ACTIVE
        run: |
          CLUSTER=$(aws cloudformation describe-stacks --stack-name "${EKS_STACK}" \
            --query "Stacks[0].Outputs[?OutputKey=='ClusterName'].OutputValue" --output text)
          aws eks wait cluster-active --name "$CLUSTER"

      # ---------- PREFLIGHT: ArgoCD ----------
      - name: Preflight - heal/delete stuck ArgoCD stack
        run: |
          set -euo pipefail
          STACK="${ARGO_STACK}"
          STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK" \
            --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NONE")
          echo "ArgoCD stack status: $STATUS"
          if [[ "$STATUS" == "ROLLBACK_FAILED" || "$STATUS" == "ROLLBACK_COMPLETE" || "$STATUS" == "DELETE_FAILED" ]]; then
            echo "Attempting delete of $STACK ..."
            aws cloudformation delete-stack --stack-name "$STACK" || true
            if ! aws cloudformation wait stack-delete-complete --stack-name "$STACK"; then
              echo "Delete failed; retaining blockers..."
              mapfile -t FAILS < <(
                aws cloudformation describe-stack-events --stack-name "$STACK" --max-items 200 \
                  --query "reverse(StackEvents)[?contains(ResourceStatus,'DELETE_FAILED')].[LogicalResourceId]" \
                  --output text | awk '!seen[$0]++'
              )
              echo "Retaining: ${FAILS[*]:-<none>}"
              if [[ "${#FAILS[@]}" -gt 0 ]]; then
                aws cloudformation delete-stack --stack-name "$STACK" --retain-resources ${FAILS[*]} || true
                aws cloudformation wait stack-delete-complete --stack-name "$STACK" || true
              fi
            fi
          else
            echo "No preflight action needed."
          fi

      - name: Bootstrap Argo CD (CFN -> CodeBuild -> Argo install)
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/argocd-bootstrap.yaml \
            --stack-name "${ARGO_STACK}" \
            --parameter-overrides \
              ClusterName=demo-eks-dev \
              Region=${{ env.AWS_REGION }} \
              KubernetesNamespace=argocd \
              ExposeServerAsLB=true \
              SSMParamPrefix=/eks/${{ env.ENV }} \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      - name: Show ArgoCD stack failure events (if any)
        if: failure()
        run: |
          aws cloudformation describe-stack-events --stack-name "${ARGO_STACK}" \
            --max-items 60 \
            --query "StackEvents[?ends_with(ResourceStatus,'FAILED')].[Timestamp,LogicalResourceId,ResourceStatus,ResourceStatusReason]" \
            --output table || true

      # ---------- PREFLIGHT: Nodegroup ----------
      - name: Preflight - heal/delete stuck Nodegroup stack
        run: |
          set -euo pipefail
          STACK="${NG_STACK}"
          STATUS=$(aws cloudformation describe-stacks --stack-name "$STACK" \
            --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NONE")
          echo "Nodegroup stack status: $STATUS"
          if [[ "$STATUS" == "ROLLBACK_FAILED" || "$STATUS" == "ROLLBACK_COMPLETE" || "$STATUS" == "DELETE_FAILED" ]]; then
            aws cloudformation delete-stack --stack-name "$STACK" || true
            if ! aws cloudformation wait stack-delete-complete --stack-name "$STACK"; then
              mapfile -t FAILS < <(
                aws cloudformation describe-stack-events --stack-name "$STACK" --max-items 200 \
                  --query "reverse(StackEvents)[?contains(ResourceStatus,'DELETE_FAILED')].[LogicalResourceId]" \
                  --output text | awk '!seen[$0]++'
              )
              [[ ${#FAILS[@]} -gt 0 ]] && aws cloudformation delete-stack --stack-name "$STACK" --retain-resources ${FAILS[*]} || true
              aws cloudformation wait stack-delete-complete --stack-name "$STACK" || true
            fi
          fi

      - name: Create/Update node group
        run: |
          PARAMS=$(jq -r '.Parameters | to_entries[] | "\(.key)=\(.value)"' cloudformation/parameters/${ENV}/nodegroup.json)
          aws cloudformation deploy \
            --template-file cloudformation/nodegroup.yaml \
            --stack-name "${NG_STACK}" \
            --parameter-overrides $PARAMS PublicSubnetIds="${{ steps.vpc.outputs.public_subnets }}" \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      # ---------- Failure event dumps (helpful on error) ----------
      - name: Show EKS stack failure events (if any)
        if: failure()
        run: |
          aws cloudformation describe-stack-events --stack-name "${EKS_STACK}" \
            --max-items 40 \
            --query "StackEvents[?ends_with(ResourceStatus,'FAILED')].[Timestamp,LogicalResourceId,ResourceStatus,ResourceStatusReason]" \
            --output table

      - name: Show Nodegroup stack failure events (if any)
        if: failure()
        run: |
          aws cloudformation describe-stack-events --stack-name "${NG_STACK}" \
            --max-items 40 \
            --query "StackEvents[?ends_with(ResourceStatus,'FAILED')].[Timestamp,LogicalResourceId,ResourceStatus,ResourceStatusReason]" \
            --output table